import os

PLAIN_HTTP = (os.environ.get("PLAIN_HTTP", "no").lower() == "yes")
SERVER_PORT = int(os.environ.get("SERVER_PORT", "12001"))
INCLUDE_USAGE_STATISTICS = (os.environ.get("INCLUDE_USAGE_STATISTICS", "no").lower() == "yes")
USAGE_STATISTICS_MAX_SAMPLES = int(os.environ.get("USAGE_STATISTICS_MAX_SAMPLES", "1000"))
AUTH_USERNAME = os.environ.get("AUTH_USERNAME", "prov_user")
AUTH_PASSWORD = os.environ.get("AUTH_PASSWORD", "prov_password")

PUBLIC_OPENEHR_API_BASE_URI = os.environ.get("PUBLIC_OPENEHR_API_BASE_URI", "http://127.0.0.1:12000")
PRIVATE_OPENEHR_API_BASE_URI = os.environ.get("PRIVATE_OPENEHR_API_BASE_URI", "http://127.0.0.1:8080/ehrbase/rest/openehr")
OPENEHR_API_AUTH_USERNAME = os.environ.get("OPENEHR_API_AUTH_USERNAME", "ehrbase-admin")
OPENEHR_API_AUTH_PASSWORD = os.environ.get("OPENEHR_API_AUTH_PASSWORD", "EvenMoreSecretPassword")
VALIDATE_OPENEHR_API_CERTIFICATE = (os.environ.get("VALIDATE_OPENEHR_API_CERTIFICATE", "no").lower() == "yes")
USE_CUSTOM_OPENEHR_API_CA_CERTIFICATE = (os.environ.get("USE_CUSTOM_OPENEHR_API_CA_CERTIFICATE", "no").lower() == "yes")

PUBLIC_DEMOGRAPHIC_API_BASE_URI = os.environ.get("PUBLIC_DEMOGRAPHIC_API_BASE_URI", "http://127.0.0.1:12000")
PRIVATE_DEMOGRAPHIC_API_BASE_URI = os.environ.get("PRIVATE_DEMOGRAPHIC_API_BASE_URI", "http://127.0.0.1:12002")
DEMOGRAPHIC_API_AUTH_USERNAME = os.environ.get("DEMOGRAPHIC_API_AUTH_USERNAME", "demographic_user")
DEMOGRAPHIC_API_AUTH_PASSWORD = os.environ.get("DEMOGRAPHIC_API_AUTH_PASSWORD", "demographic_password")
VALIDATE_DEMOGRAPHIC_API_CERTIFICATE = (os.environ.get("VALIDATE_DEMOGRAPHIC_API_CERTIFICATE", "no").lower() == "yes")
USE_CUSTOM_DEMOGRAPHIC_API_CA_CERTIFICATE = (os.environ.get("USE_CUSTOM_DEMOGRAPHIC_API_CA_CERTIFICATE", "no").lower() == "yes")
